M48
; DRILL file {KiCad 8.0.3} date 2025-09-30T21:19:29-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-30T21:19:29-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
%
G90
G05
T1
X159.515Y-128.804
X159.515Y-130.836
X164.595Y-129.82
M30
